### ISSUE TITLE
502 Bad gateway while executing sql-review.sh script

### ISSUE THREAD

**Issue by jozef-valko** [bytebase/sql-review-action#19]
Hi all,
we are facing the 502 Bad gateway problem while executing this GH action. API endpoint https://sql.bytebase.com/ is unreachable. Could you please assist?

![image](https://user-images.githubusercontent.com/18370624/234026420-1235c32c-f76b-4698-87c7-bb9a88dd734d.png)

Thank you.

**Comment by d-bytebase** [comment]
Hi @jozef-valko, our server had reached resource limit. We've been actively spinning up more resources, and it should be working again. Sorry about the issue. Btw, feel free to join our community and message us if you have any questions. Thanks!

https://www.bytebase.com/docs/faq#how-to-reach-us
